# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-26 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField()),
                ('value', models.IntegerField()),
                ('created_date', models.DateField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondaryTestModel',
            fields=[
                ('id', models.AutoField()),
                ('value', models.IntegerField()),
                ('created_date', models.DateField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
